// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Bn1PvTgapQg6Bp1f0DckCZ1Agy8sdqA',
    appId: '1:707464102007:web:21e705c7e954db13298672',
    messagingSenderId: '707464102007',
    projectId: 'tripify-xie',
    authDomain: 'tripify-xie.firebaseapp.com',
    storageBucket: 'tripify-xie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOXvlJFphlSlhiCxTx7vltXCeo1Xg0u-4',
    appId: '1:707464102007:android:f44c0a8296712e8d298672',
    messagingSenderId: '707464102007',
    projectId: 'tripify-xie',
    storageBucket: 'tripify-xie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLOK6i0KZDlhsSps5BNgkiwWDay7FDr4c',
    appId: '1:707464102007:ios:e5b3356b82dd1bea298672',
    messagingSenderId: '707464102007',
    projectId: 'tripify-xie',
    storageBucket: 'tripify-xie.firebasestorage.app',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLOK6i0KZDlhsSps5BNgkiwWDay7FDr4c',
    appId: '1:707464102007:ios:e5b3356b82dd1bea298672',
    messagingSenderId: '707464102007',
    projectId: 'tripify-xie',
    storageBucket: 'tripify-xie.firebasestorage.app',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Bn1PvTgapQg6Bp1f0DckCZ1Agy8sdqA',
    appId: '1:707464102007:web:533a2b8d81f3c99b298672',
    messagingSenderId: '707464102007',
    projectId: 'tripify-xie',
    authDomain: 'tripify-xie.firebaseapp.com',
    storageBucket: 'tripify-xie.firebasestorage.app',
  );
}
